UI = {
    "ru": {
        "home": "Главная",
        "catalog": "Каталог",
        "about": "О нас",
        "contacts": "Контакты",
        "rent": "Арендовать",
        "rental": "Аренда",
        "made_to_order": "На заказ",
        "ready_made": "Готовые изделия",
        "discover": "Смотреть коллекцию",
        "book": "Забронировать",
        "buy": "Уточнить покупку",
        "price_from": "от",
        "colors": "Цвета",
        "sizes": "Размеры",
        "availability": "Календарь бронирования",
        "select_dates": "Выберите даты",
        "name": "Имя",
        "phone": "Телефон",
        "email": "Email",
        "message": "Сообщение",
        "send": "Отправить",
        "all": "Все",
        "filter": "Фильтры",
        "ready": "Готовое",
        "custom": "Индивидуальный пошив",
        "viewer360": "360° обзор",
        "category": "Категория",
        "color": "Цвет",
        "size": "Размер",
        "max_price": "Цена до",
        "sort": "Сортировка",
        "results": "изделий",
        "clear_filters": "Сбросить",
        "apply_filters": "Применить",
        "featured_sort": "Рекомендуемые",
        "newest_sort": "Новинки",
        "price_low_sort": "Цена: по возрастанию",
        "price_high_sort": "Цена: по убыванию",
        "name_sort": "По названию",
        "collection": "Коллекция",
        "empty_catalog": "По выбранным фильтрам ничего не найдено.",
    },
    "en": {
        "home": "Home",
        "catalog": "Catalog",
        "about": "About",
        "contacts": "Contacts",
        "rent": "Rent",
        "rental": "Rental",
        "made_to_order": "Made to order",
        "ready_made": "Ready made",
        "discover": "Discover collection",
        "book": "Book now",
        "buy": "Ask about purchase",
        "price_from": "from",
        "colors": "Colors",
        "sizes": "Sizes",
        "availability": "Booking calendar",
        "select_dates": "Select dates",
        "name": "Name",
        "phone": "Phone",
        "email": "Email",
        "message": "Message",
        "send": "Send",
        "all": "All",
        "filter": "Filters",
        "ready": "Ready made",
        "custom": "Made to order",
        "viewer360": "360° view",
        "category": "Category",
        "color": "Color",
        "size": "Size",
        "max_price": "Price up to",
        "sort": "Sort",
        "results": "pieces",
        "clear_filters": "Clear",
        "apply_filters": "Apply",
        "featured_sort": "Featured",
        "newest_sort": "Newest",
        "price_low_sort": "Price: low to high",
        "price_high_sort": "Price: high to low",
        "name_sort": "By name",
        "collection": "Collection",
        "empty_catalog": "No pieces match the selected filters.",
    },
}


def site_context(request):
    lang = request.session.get("site_lang", "ru")
    if lang not in UI:
        lang = "ru"
    return {"site_lang": lang, "ui": UI[lang]}
