UI = {
    "az": {
        "home": "Ana səhifə",
        "catalog": "Kataloq",
        "about": "Haqqımızda",
        "contacts": "Əlaqə",
        "rent": "Kirayələ",
        "rental": "Kirayə",
        "made_to_order": "Sifarişlə",
        "ready_made": "Hazır geyimlər",
        "discover": "Kolleksiyaya bax",
        "book": "Bron et",
        "buy": "Alış barədə soruş",
        "price_from": "başlayaraq",
        "colors": "Rənglər",
        "sizes": "Ölçülər",
        "availability": "Bron təqvimi",
        "select_dates": "Tarixləri seçin",
        "name": "Ad",
        "phone": "Telefon",
        "email": "Email",
        "message": "Qeyd",
        "send": "Göndər",
        "all": "Hamısı",
        "filter": "Filtrlər",
        "ready": "Hazır",
        "custom": "Fərdi tikiş",
        "viewer360": "360° baxış",
        "category": "Kateqoriya",
        "color": "Rəng",
        "size": "Ölçü",
        "max_price": "Maksimum qiymət",
        "sort": "Sıralama",
        "results": "məhsul",
        "clear_filters": "Təmizlə",
        "apply_filters": "Tətbiq et",
        "featured_sort": "Tövsiyə olunan",
        "newest_sort": "Yenilər",
        "price_low_sort": "Qiymət: aşağıdan yuxarı",
        "price_high_sort": "Qiymət: yuxarıdan aşağı",
        "name_sort": "Ada görə",
        "collection": "Kolleksiya",
        "empty_catalog": "Seçilmiş filtrlərə uyğun məhsul tapılmadı.",
        "choose_size": "Ölçü seçin",
        "choose_color": "Rəng seçin",
        "booking_hint": "Əvvəl rəng və ölçünü, sonra uyğun tarix aralığını seçin.",
        "calendar_free": "Boş",
        "calendar_booked": "Bron olunub",
        "calendar_selected": "Seçilib",
        "calendar_past": "Keçmiş",
        "booking_days": "gün",
        "booking_pending": "Sorğunuz qəbul edildi. Təsdiqdən sonra bron qüvvəyə minəcək.",
        "booking_code": "Bron kodu",
        "booking_error": "Bron yaratmaq mümkün olmadı. Məlumatları yoxlayın.",
        "booking_unavailable": "Seçilmiş tarix aralığında artıq bron olunmuş gün var.",
        "select_period_first": "Əvvəl tarix aralığını seçin.",
        "select_color_first": "Əvvəl rəng seçin.",
        "select_size_first": "Əvvəl ölçü seçin.",
        "week_mon": "Be",
        "week_tue": "Ça",
        "week_wed": "Ç",
        "week_thu": "Ca",
        "week_fri": "C",
        "week_sat": "Ş",
        "week_sun": "B",
    },
    "ru": {
        "home": "Главная",
        "catalog": "Каталог",
        "about": "О нас",
        "contacts": "Контакты",
        "rent": "Арендовать",
        "rental": "Аренда",
        "made_to_order": "На заказ",
        "ready_made": "Готовые изделия",
        "discover": "Смотреть коллекцию",
        "book": "Забронировать",
        "buy": "Уточнить покупку",
        "price_from": "от",
        "colors": "Цвета",
        "sizes": "Размеры",
        "availability": "Календарь бронирования",
        "select_dates": "Выберите даты",
        "name": "Имя",
        "phone": "Телефон",
        "email": "Email",
        "message": "Комментарий",
        "send": "Отправить",
        "all": "Все",
        "filter": "Фильтры",
        "ready": "Готовое",
        "custom": "Индивидуальный пошив",
        "viewer360": "360° обзор",
        "category": "Категория",
        "color": "Цвет",
        "size": "Размер",
        "max_price": "Цена до",
        "sort": "Сортировка",
        "results": "изделий",
        "clear_filters": "Сбросить",
        "apply_filters": "Применить",
        "featured_sort": "Рекомендуемые",
        "newest_sort": "Новинки",
        "price_low_sort": "Цена: по возрастанию",
        "price_high_sort": "Цена: по убыванию",
        "name_sort": "По названию",
        "collection": "Коллекция",
        "empty_catalog": "По выбранным фильтрам ничего не найдено.",
        "choose_size": "Выберите размер",
        "choose_color": "Выберите цвет",
        "booking_hint": "Сначала выберите цвет и размер, затем свободный период.",
        "calendar_free": "Свободно",
        "calendar_booked": "Занято",
        "calendar_selected": "Выбрано",
        "calendar_past": "Прошло",
        "booking_days": "дн.",
        "booking_pending": "Заявка принята. Бронь вступит в силу после подтверждения.",
        "booking_code": "Код брони",
        "booking_error": "Не удалось создать бронь. Проверьте данные.",
        "booking_unavailable": "В выбранном периоде уже есть занятые даты.",
        "select_period_first": "Сначала выберите период.",
        "select_color_first": "Сначала выберите цвет.",
        "select_size_first": "Сначала выберите размер.",
        "week_mon": "Пн",
        "week_tue": "Вт",
        "week_wed": "Ср",
        "week_thu": "Чт",
        "week_fri": "Пт",
        "week_sat": "Сб",
        "week_sun": "Вс",
    },
    "en": {
        "home": "Home",
        "catalog": "Catalog",
        "about": "About",
        "contacts": "Contacts",
        "rent": "Rent",
        "rental": "Rental",
        "made_to_order": "Made to order",
        "ready_made": "Ready made",
        "discover": "Discover collection",
        "book": "Book now",
        "buy": "Ask about purchase",
        "price_from": "from",
        "colors": "Colors",
        "sizes": "Sizes",
        "availability": "Booking calendar",
        "select_dates": "Select dates",
        "name": "Name",
        "phone": "Phone",
        "email": "Email",
        "message": "Note",
        "send": "Send",
        "all": "All",
        "filter": "Filters",
        "ready": "Ready made",
        "custom": "Made to order",
        "viewer360": "360° view",
        "category": "Category",
        "color": "Color",
        "size": "Size",
        "max_price": "Price up to",
        "sort": "Sort",
        "results": "pieces",
        "clear_filters": "Clear",
        "apply_filters": "Apply",
        "featured_sort": "Featured",
        "newest_sort": "Newest",
        "price_low_sort": "Price: low to high",
        "price_high_sort": "Price: high to low",
        "name_sort": "By name",
        "collection": "Collection",
        "empty_catalog": "No pieces match the selected filters.",
        "choose_size": "Choose size",
        "choose_color": "Choose color",
        "booking_hint": "Choose a color and size first, then select an available date range.",
        "calendar_free": "Available",
        "calendar_booked": "Booked",
        "calendar_selected": "Selected",
        "calendar_past": "Past",
        "booking_days": "days",
        "booking_pending": "Request received. The booking becomes active after confirmation.",
        "booking_code": "Booking code",
        "booking_error": "Could not create the booking. Check the details.",
        "booking_unavailable": "The selected range contains unavailable dates.",
        "select_period_first": "Select a date range first.",
        "select_color_first": "Choose a color first.",
        "select_size_first": "Choose a size first.",
        "week_mon": "Mo",
        "week_tue": "Tu",
        "week_wed": "We",
        "week_thu": "Th",
        "week_fri": "Fr",
        "week_sat": "Sa",
        "week_sun": "Su",
    },
}


def site_context(request):
    lang = request.session.get("site_lang", "az")
    if lang not in UI:
        lang = "az"
    return {"site_lang": lang, "ui": UI[lang]}
