# Generated by Django 5.2.17 on 2026-09-26 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_product_moderation_note_product_moderation_status_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['sort_order', 'name_ru'], 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='color',
            options={'ordering': ['name_ru'], 'verbose_name': 'Color', 'verbose_name_plural': 'Colors'},
        ),
        migrations.AlterModelOptions(
            name='contactmessage',
            options={'ordering': ['-created_at'], 'verbose_name': 'Contact message', 'verbose_name_plural': 'Contact messages'},
        ),
        migrations.AlterModelOptions(
            name='favorite',
            options={'ordering': ['-created_at'], 'verbose_name': 'Favorite', 'verbose_name_plural': 'Favorites'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-is_featured', '-id'], 'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.AlterModelOptions(
            name='productimage',
            options={'ordering': ['image_type', 'color_id', 'sort_order', 'angle', 'id'], 'verbose_name': 'Product photo', 'verbose_name_plural': 'Product photos'},
        ),
        migrations.AlterModelOptions(
            name='productvideo',
            options={'ordering': ['color_id', 'sort_order', 'id'], 'verbose_name': 'Product video', 'verbose_name_plural': 'Product videos'},
        ),
        migrations.AlterModelOptions(
            name='reservation',
            options={'ordering': ['-created_at'], 'verbose_name': 'Reservation', 'verbose_name_plural': 'Reservations'},
        ),
        migrations.AlterModelOptions(
            name='sitesettings',
            options={'verbose_name': 'Site settings', 'verbose_name_plural': 'Site settings'},
        ),
        migrations.AlterField(
            model_name='product',
            name='moderation_status',
            field=models.CharField(choices=[('pending', 'Pending moderation'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='approved', max_length=12),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('rental', 'Rental'), ('ready', 'Ready to wear'), ('custom', 'Made to order')], default='rental', max_length=12),
        ),
        migrations.AlterField(
            model_name='product',
            name='rental_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Rental price per calendar day.', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='source',
            field=models.CharField(choices=[('couture', 'Couture'), ('user', 'Customer')], default='couture', max_length=12),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='angle',
            field=models.PositiveSmallIntegerField(default=0, help_text='Not used for the regular gallery.'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image_type',
            field=models.CharField(choices=[('gallery', 'Gallery photo')], default='gallery', max_length=12),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending confirmation'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], default='pending', max_length=12),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='whatsapp_phone',
            field=models.CharField(blank=True, help_text='Example: +994501234567. Leave empty to hide the WhatsApp button.', max_length=60),
        ),
    ]
